# Generated by Django 3.2.7 on 2023-01-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(default='', upload_to='project_icons/'),
        ),
    ]
