# Generated by Django 3.2.7 on 2023-01-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='icon',
        ),
    ]
