# Generated by Django 3.2.7 on 2023-01-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(default=None, upload_to='project_icons/'),
            preserve_default=False,
        ),
    ]
