# Generated by Django 4.1.6 on 2023-02-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='purpose_en',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('w', 'web'), ('a', 'application'), ('e', 'else')], default='w', max_length=1),
        ),
    ]
